on:
  pull_request:
    branches:
      - master

name: Check PR

jobs:
  pr_check:
    name: PR Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Build with Gradle
        run: ./gradlew clean test
